name: "ZXF: Merge Queue Controller"
on:
  push:
    branches:
      - trunk-merge/**
defaults:
  run:
    shell: bash

permissions:
  contents: read

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: "Merge Queue"
    uses: ./.github/workflows/zxc-code-compiles.yaml
    with:
      custom-job-label: "Build"

  unit-tests:
    name: "Merge Queue"
    uses: ./.github/workflows/zxc-unit-test.yaml
    needs:
      - build
    with:
      custom-job-label: "Unit Tests"
